// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ViewCard$ReactTemplate = require("./ViewCard.bs.js");

var component = ReasonReact.statelessComponent("Hand");

function make(hand, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, $$Array.of_list(List.mapi((function (idx, card) {
                            return React.createElement("span", {
                                        key: String(idx)
                                      }, ReasonReact.element(/* None */0, /* None */0, ViewCard$ReactTemplate.make(card, /* array */[])));
                          }), hand)));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
