// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PokerPrompt");

function make(prompt, onPrompt, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      if (prompt !== 0) {
        return React.createElement("a", {
                    onClick: (function () {
                        return Curry._1(onPrompt, /* Prompt */1);
                      })
                  }, "Prompt");
      } else {
        return React.createElement("a", {
                    onClick: (function () {
                        return Curry._1(onPrompt, /* Deal */0);
                      })
                  }, "Deal");
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
