// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("PokerPrompt");

function make(round, onPrompt, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = +(round === /* PreFlop */0);
      if (match !== 0) {
        return React.createElement("a", {
                    onClick: (function () {
                        return Curry._1(onPrompt, /* Deal */0);
                      })
                  }, "Deal");
      } else {
        return React.createElement("div", undefined, React.createElement("a", {
                        onClick: (function () {
                            return Curry._1(onPrompt, /* Flop */Block.__(0, [/* Check */0]));
                          })
                      }, "Check "), React.createElement("a", {
                        onClick: (function () {
                            return Curry._1(onPrompt, /* Flop */Block.__(0, [/* Bet */2]));
                          })
                      }, " Bet "), React.createElement("a", {
                        onClick: (function () {
                            return Curry._1(onPrompt, /* Flop */Block.__(0, [/* Fold */1]));
                          })
                      }, " Fold"));
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
