// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React              = require("react");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var Card$ReactTemplate = require("../Card.bs.js");

var component = ReasonReact.statelessComponent("ViewCard");

function make(card, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var cardText = Card$ReactTemplate.printCard(card);
      return React.createElement("div", undefined, cardText);
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
