// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Random   = require("bs-platform/lib/js/random.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

Random.self_init(/* () */0);

function strFromValue(value) {
  switch (value) {
    case 0 : 
        return "2";
    case 1 : 
        return "3";
    case 2 : 
        return "4";
    case 3 : 
        return "5";
    case 4 : 
        return "6";
    case 5 : 
        return "7";
    case 6 : 
        return "8";
    case 7 : 
        return "9";
    case 8 : 
        return "10";
    case 9 : 
        return "11";
    case 10 : 
        return "Q";
    case 11 : 
        return "K";
    case 12 : 
        return "A";
    
  }
}

function intFromValue(value) {
  return value + 2 | 0;
}

function strFromSuit(suit) {
  switch (suit) {
    case 0 : 
        return "Diamonds";
    case 1 : 
        return "Spades";
    case 2 : 
        return "Hearts";
    case 3 : 
        return "Clubs";
    
  }
}

function printCard(card) {
  return strFromValue(card[0]) + (" " + strFromSuit(card[1]));
}

function compareCard(card1, card2) {
  var intValue1 = card1[0] + 2 | 0;
  var intValue2 = card2[0] + 2 | 0;
  var match = Caml_obj.caml_int_compare(intValue1, intValue2);
  var switcher = match + 1 | 0;
  if (switcher > 2 || switcher < 0) {
    return /* Tie */2;
  } else {
    switch (switcher) {
      case 0 : 
          return /* Lower */1;
      case 1 : 
          return /* Tie */2;
      case 2 : 
          return /* Higher */0;
      
    }
  }
}

var values = /* :: */[
  /* Two */0,
  /* :: */[
    /* Three */1,
    /* :: */[
      /* Four */2,
      /* :: */[
        /* Five */3,
        /* :: */[
          /* Six */4,
          /* :: */[
            /* Seven */5,
            /* :: */[
              /* Eight */6,
              /* :: */[
                /* Nine */7,
                /* :: */[
                  /* Ten */8,
                  /* :: */[
                    /* Jack */9,
                    /* :: */[
                      /* Queen */10,
                      /* :: */[
                        /* King */11,
                        /* :: */[
                          /* Ace */12,
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var suits = /* :: */[
  /* Diamonds */0,
  /* :: */[
    /* Spades */1,
    /* :: */[
      /* Hearts */2,
      /* :: */[
        /* Clubs */3,
        /* [] */0
      ]
    ]
  ]
];

exports.values       = values;
exports.suits        = suits;
exports.strFromValue = strFromValue;
exports.intFromValue = intFromValue;
exports.strFromSuit  = strFromSuit;
exports.printCard    = printCard;
exports.compareCard  = compareCard;
/*  Not a pure module */
