// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Random                  = require("bs-platform/lib/js/random.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function computePrompt(_, _$1) {
  var rand = Random.$$int(2);
  if (rand > 2 || rand < 0) {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "/Users/lylegarza/projects/reason_casino/src/Player.re",
            5,
            2
          ]
        ];
  } else {
    return rand;
  }
}

exports.computePrompt = computePrompt;
/* No side effect */
