// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List   = require("bs-platform/lib/js/list.js");
var Random = require("bs-platform/lib/js/random.js");

function processComputerPlayerPrompt(_, _$1) {
  var rand = Random.$$int(2);
  if (rand > 2 || rand < 0) {
    return /* Check */0;
  } else {
    return rand;
  }
}

function processPlayer(player, dealer, prompts) {
  var playerPrompt = List.find((function (x) {
          return +(x[/* id */0] === player[/* id */0]);
        }), prompts);
  var match = playerPrompt[/* prompt */1];
  var wager = match >= 2 ? 100 : 0;
  var newDealer_000 = /* id */dealer[/* id */0];
  var newDealer_001 = /* hand */dealer[/* hand */1];
  var newDealer_002 = /* money */dealer[/* money */2] + wager | 0;
  var newDealer_003 = /* name */dealer[/* name */3];
  var newDealer_004 = /* src */dealer[/* src */4];
  var newDealer = /* record */[
    newDealer_000,
    newDealer_001,
    newDealer_002,
    newDealer_003,
    newDealer_004
  ];
  var newPlayer_000 = /* id */player[/* id */0];
  var newPlayer_001 = /* hand */player[/* hand */1];
  var newPlayer_002 = /* money */player[/* money */2] - wager | 0;
  var newPlayer_003 = /* name */player[/* name */3];
  var newPlayer_004 = /* src */player[/* src */4];
  var newPlayer = /* record */[
    newPlayer_000,
    newPlayer_001,
    newPlayer_002,
    newPlayer_003,
    newPlayer_004
  ];
  return /* tuple */[
          newPlayer,
          newDealer
        ];
}

function processPlayers(_processedPlayers, _players, _dealer, prompts) {
  while(true) {
    var dealer = _dealer;
    var players = _players;
    var processedPlayers = _processedPlayers;
    if (players) {
      var match = processPlayer(players[0], dealer, prompts);
      _dealer = match[1];
      _players = players[1];
      _processedPlayers = List.append(processedPlayers, /* :: */[
            match[0],
            /* [] */0
          ]);
      continue ;
      
    } else {
      return /* tuple */[
              processedPlayers,
              dealer
            ];
    }
  };
}

exports.processComputerPlayerPrompt = processComputerPlayerPrompt;
exports.processPlayer               = processPlayer;
exports.processPlayers              = processPlayers;
/* No side effect */
