// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List               = require("bs-platform/lib/js/list.js");
var Pervasives         = require("bs-platform/lib/js/pervasives.js");
var Card$ReactTemplate = require("./Card.bs.js");
var Deck$ReactTemplate = require("./Deck.bs.js");

function dealToPlayers(_board, _playersToBeDelt, numCards) {
  while(true) {
    var playersToBeDelt = _playersToBeDelt;
    var board = _board;
    if (playersToBeDelt) {
      var match = Deck$ReactTemplate.getCards(/* [] */0, board[0], numCards);
      var playerWithNewCard_000 = /* id */playersToBeDelt[0][/* id */0];
      var playerWithNewCard_001 = /* hand */match[0];
      var playerWithNewCard = /* record */[
        playerWithNewCard_000,
        playerWithNewCard_001
      ];
      var newPlayers = List.append(board[1], /* :: */[
            playerWithNewCard,
            /* [] */0
          ]);
      var newBoard_000 = match[1];
      var newBoard = /* tuple */[
        newBoard_000,
        newPlayers
      ];
      _playersToBeDelt = playersToBeDelt[1];
      _board = newBoard;
      continue ;
      
    } else {
      return board;
    }
  };
}

function dealFlop(deck, players) {
  var board = /* tuple */[
    deck,
    /* [] */0
  ];
  return dealToPlayers(board, players, 2);
}

function deal(players) {
  var deck = Deck$ReactTemplate.makeDeck(/* () */0);
  var shuffledDeck = Deck$ReactTemplate.shuffle(deck);
  return dealFlop(shuffledDeck, players);
}

function printPlayers(players) {
  return List.map((function (player) {
                console.log("****** Player " + (Pervasives.string_of_int(player[/* id */0]) + " *******"));
                return List.map((function (card) {
                              console.log(Card$ReactTemplate.printCard(card));
                              return /* () */0;
                            }), player[/* hand */1]);
              }), players);
}

exports.dealToPlayers = dealToPlayers;
exports.dealFlop      = dealFlop;
exports.deal          = deal;
exports.printPlayers  = printPlayers;
/* Card-ReactTemplate Not a pure module */
